# Generated by Django 4.2.10 on 2025-04-20 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='contratos/adjuntos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('servicio', 'Servicio'), ('obra', 'Obra'), ('suministro', 'Suministro'), ('otro', 'Otro')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('parte_a', models.CharField(help_text='Primera parte del contrato (ej. Conjunto Residencial)', max_length=200)),
                ('parte_b', models.CharField(help_text='Segunda parte del contrato (ej. Proveedor)', max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion_cambio', models.TextField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='contratos.contrato')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
