# Generated by Django 4.2.10 on 2025-04-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('vencido', 'Vencido'), ('no_iniciado', 'No Iniciado')], default='no_iniciado', max_length=20),
        ),
    ]
